r3:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  right_blade_controller:
    type: velocity_controllers/JointVelocityController
    joint: blade_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
